þVôôVþVôôVVVVVþVôôVVVVVVVVVþVVWWVôôVVVVVVVVVþVôôôVVWWVôôVVVVVVVVVþ
VôôVVVVVVVWWVôôVVVVVVVVVþVôôVVVVVVVVVVVWWVôôVVVVVVVVVþVôôVVVVVVVVVVVVVVVWWVôôVVVVVVVWWþVVVVVVVVVVVVVVVVVVWWVôôôVVWWþVVVVVVVVVVVVVVVVVVWWVVWWþ
VVVVVVVVVVVVVVVVVVWWþVVVVVVVVVVVVVVWWþVVVVVVVVVVWWþVVVVVVWWþVVWWÿþVôôVþVôôVVVVVþVôôVVVVVVVVVþVôôVVVVVVVVVVVVVþVôôVVVVVVVVVVVVVVVVVþ
VôôVVVVVVVVVVVVVVVVVVVVVþVVWWVôôVVVVVVVVVVVVVVVVVVVVVþVôôôVVWWVôôVVVVVVVVVVVVVVVVVVVWWþVVVVVVWWVôôVVVVVVVVVVVVVVVWWþVVVVVVWWVôôVVVVVVVVVVVWWþ
VVVVVVWWVôôVVVVVVVWWþVVVVVVWWVôôôVVWWþVVVVVVWWVVWWþVVVVVVWWþVVWWÿþVôôVþVôôVVVVVþVôôVVVVVVVVVþVôXX\ðWV\\Uó\ðVVþX\ðX]]]]\X\XXW\XX\ðóþ
\ð]]]]]]]\]\XX]\\\WXX\ðóþVX]]]]]]X\]]]]\XXXWW\WXXXXóVþVôô]]\]\]]]\]]\\X]X]XX]XW]WXXVWWþV]]]]X]\X\]\]]\\\\\XXW\XXXXWþ]]]]]]]\]\\\X\]X\]WX\WXWþ
]]]X]]]]\X]\\\XWXXXXþVV]]]]]]]]]XXXWWþVVVVVVWWVVWWþVVVVVVWWþVVWWÿþWõõWþWõõWWWWWþWõõWWWWWWWWWþWWXXWõõWWWWWWWWWþWõõõWWXXWõõWWWWWWWWWþ
WõõWWWWWWWXXWõõWWWWWWWWWþWõõWWWWWWWWWWWXXWõõWWWWWWWWWþWõõWWWWWWWWWWWWWWWXXWõõWWWWWWWXXóõWWWWWWWWWWWWWWWWWWXXWõõWWWXXYYóVVõWWWWWWWWWWWWWWWWWWXXXõXXYYYYóVVVVõWWWWWWWWWWWWWWWWWWXYTYYYYYóVVVVVVõWWWWWWWWWWWWWWXXYWTYYYYYVVVVVVVVVõWWWWWWWWWWXXYYYWTYYYYWRTWVVVVVVVVõWWWWWWXXYYYYYWTYYWVTPPRTWVVVVVVVVõWWXXYYYYYYYWTWVTRSPPRPRTWVVVVVVVVTYYYYYYYYYWVTRRRTPRTPPPRTWVVVVVVTYYYYYYYWVTRSPRRRTRPPPPRPRTWVVVVTYYYYYWVTRRRTSRTVXYTRPRTPPPRTWVVTYYYWVTRSPRRRTVYXþXYTRPPPPRPRTWTYWVTRRRTSRTVYXþXYTRPRTPPPRTVTRSPRRRTVYXþ
XYTRPPPPRPRRRTSRTVYXþXYTRPRTPPRRRTVYXþXYTRPPSRTVYXþXYTRTVYXþXYYXÿþWõõWþWõõWWWWWþWõõWWWWWWWWWþWõõWWWWWWWWWWWWWþWõõWWWWWWWWWWWWWWWWWþ
WõõWWWWWWWWWWWWWWWWWWWWWþWWXXWõõWWWWWWWWWWWWWWWWWWWWWþWõõõWWXXWõõWWWWWWWWWWWWWWWWWWWXXóõWWWWWWXXWõõWWWWWWWWWWWWWWWXXYYóVVõWWWWWWXXWõõWWWWWWWWWWWXXYYYYóVVVVõWWWWWWXXWõõWWWWWWWXXYYYYYYóVVVVVVõWWWWWWXXWõõõWWXXYYYYYYYYVVVVVVVVVõWWWWWWXXWWXXYYYYYYYYYWRTWVVVVVVVVõWWWWWWXXTYYYYYYYYWVTPPRTWVVVVVVVVõWWXXYWTYYYYYYWVTRSPPRPRTWVVVVVVVVTYYYWTYYYYWVTRRRTPRTPPPRTWVVVVVVTYYYWTYYWVTRSPRRRTRPPPPRPRTWVVVVTYYYWTWVTRRRTSRTVXYTRPRTPPPRTWVVTYYYWVTRSPRRRTVYXþXYTRPPPPRPRTWTYWVTRRRTSRTVYXþXYTRPRTPPPRTVTRSPRRRTVYXþ
XYTRPPPPRPRRRTSRTVYXþXYTRPRTPPRRRTVYXþXYTRPPSRTVYXþXYTRTVYXþXYYXÿþVVVVþVVVVVVVVþVVVVVVVVVVVVþVVXX\RWV\\UU\RVVþX\RX]]]]\X\XXW\XX\RUþ
\R]]]]]]]\]\XX]\\\WXX\RUþVX]]]]]]X\]]]]\XXXWW\WXXXXUVþVVV]]\]\]]]\]]\\X]X]XX]XW]WXXVWWTVW]]]]X]\X\]\]]\\\\\XXW\XXXXWXXTUVX]\]]]]]\]\\\X\]X\WWX\WXWXXXXTUUV]]]]]X]]]]\X]\\\XWXX\\XXXXXXTUUV\]]\]]]\]]]]]]]XXX\\XX\\\XXXUUV\XW]]\]]]\XWVW\V\\W\XWXWX\XX\QS\XUUX]]]XVVVVVVV\\\XXWXXXXX\USPPQSVUUW]]\VUVVVWW\\X\\WW\Y\USQRP°QPQSVUUW\\WUUYXXXX\\X\X\USQQQSPQSPPPQSVUUW\\WYXXXXXX\\USQRPQQQSQPPP°QPQSVU\UUYXXXXX\USQQQSRQSUWXSQPQSPPPQS\UUYXXX\USQRPQQQSUXWþWXSQPPP°QPQSVYX\USQQQSRQSUXWþWXSQPQSPPPQSUSQRPQQQSUXWþ
WXSQPPP°QPQQQSRQSUXWþWXSQPQSPPQQQSUXWþWXSQPPRQSUXWþWXSQSUXWþWXXWÿþWWWWþWWWWWWWWþWWWWWWWWWWWWþWWWWWWWWWWWWWWWWþWWWWWWWWWWWWWWWWWWWWþ
WWWWWWWWWWWWWWWWWWWWWWWWþWWWWWWWWWWWWWWWWWWWWWWWWWWWWþWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXóõWWWWWWWWWWWWWWWWWWWWWWWWWWWXYYóVõõWWWWWWWWWWWWWWWWWWWWWWWXYYYYóVVVõõWWWWWWWWWWWWWWWWWWWXYYYYYYóVVVVVõõWWWWWWWWWWWWWWWXYYYYYYYYWVVVVVVVõõWWWWWWWWWWWXYYYYYYYYYWRTWVVVVVVVõõWWWWWWWXYYYYYYYYYWVTPPRTWVVVVVVVõõWWWXYYYYYYYYYWVTRSPPRPRTWVVVVVVVõTYYYYYYYYYWVTRRRTPRTPPPRTWVVVVVVTYYYYYYYWVTRSPRRRTRPPPPRPRTWVVVVTYYYYYWVTRRRTSRTVXYTRPRTPPPRTWVVTYYYWVTRSPRRRTVYXXYXYTRPPPPRPRTWTYWVTRRRTSRTVYXWWWWXYXYTRPRTPPPRTVTRSPRRRTVYXWXYWWWWWXYXYTRPPPPRPRRRTSRTVYXWWYYYYWVYVWVXYXYTRPRTPPRRRTVYXXWYXYYYYVYVWWWVWXYXYTRPPSRTVYXWYYWYWYYYYWVYWWYWWWYXYXYTRTVYXWWYYXYWYXWYYWWWVWWWWWWWWXYXYYXWWYWXWXXXYYWWYRTYWWWVVVWWWWWXYWWYWXWYWWYWXYYVTPPRTYWWWWWVWVWWWYYYYYYYYYYXXVTRSPPRPRTVVVWWWWYWWYXYYYYYWYYVTRRRTPRTPPPRTWVWYWWWXYYWYYXYXVTRSPRRRTRPPPPRPRTYYWWYWYYYXYWVTRRRTSRTVYYTRPRTPPPRTYVVYYYXYVTRSPRRRTVWWþYYTRPPPPRPRTWWYXVTRRRTSRTVWWþYYTRPRTPPPRTVTRSPRRRTVWWþ
YYTRPPPPRPRRRTSRTVWWþYYTRPRTPPRRRTVWWþYYTRPPSRTVWWþYYTRTVWWþYYWWÿþWWWWþWWWWWWWWþWWWWWWWWWWWWþWõYYWñXWWWVôWñWWþYWñYXXXXWYWYYXWYYWñôþ
WñXXXXXXXWXWYYXWWWXYYWñôþWYXXXXXXYWXXXXWYYYXXWXYYYYôWþWWõXXWXWXXXWXXWWYXYXYYXYXXXYYWXXóõXXXXXYXWYWXWXXWWWWWYYXWYYYYXYYóVõõXWXXXXXWXWWWYWXYWXXYWXYXYYYYóVVVõõXXXYXXXXWYXWWWYXYYWWYYYYYYóVVVVVõõXXXWXXXXXXXYYYWWYYYYYYYYWVVVVVVVõõXXWYXWXWWWWXYYYYYYYYYWRTWVVVVVVVõõWWWWWWWWYYYYYYYYYWVTPPRTWVVVVVVVõõWWXXYYYYYYYYYWVTRSPPRPRTWVVVVVVVõTYYYYYYYYYWVTRRRTPRTPPPRTWVVVVVVTYYYYYYYWVTRSPRRRTRPPPPRPRTWVVVVTYYYYYWVTRRRTSRTVXYTRPRTPPPRTWVVTYYYWVTRSPRRRTVYXXYXYTRPPPPRPRTWTYWVTRRRTSRTVYXWWWWXYXYTRPRTPPPRTVTRSPRRRTVYXWXYWWWWWXYXYTRPPPPRPRRRTSRTVYXWWYYYYWVYVWVXYXYTRPRTPPRRRTVYXXWYXYYYYVYVWWWVWXYXYTRPPSRTVYXWYYWYWYYYYWVYWWYWWWYXYXYTRTVYXWWYYXYWYXWYYWWWVWWWWWWWWXYXYYXWWYWXWXXXYYWWYRTYWWWVVVWWWWWXYWWYWXWYWWYWXYYVTPPRTYWWWWWVWVWWWYYYYYYYYYYXXVTRSPPRPRTVVVWWWWYWWYXYYYYYWYYVTRRRTPRTPPPRTWVWYWWWXYYWYYXYXVTRSPRRRTRPPPPRPRTYYWWYWYYYXYWVTRRRTSRTVYYTRPRTPPPRTYVVYYYXYVTRSPRRRTVWWþYYTRPPPPRPRTWWYXVTRRRTSRTVWWþYYTRPRTPPPRTVTRSPRRRTVWWþ
YYTRPPPPRPRRRTSRTVWWþYYTRPRTPPRRRTVWWþYYTRPPSRTVWWþYYTRTVWWþYYWWÿþVVXVþVWXWVVVWþXVVXVXXWVXVVþXXWVXVWVXXVWXXWWþVXWXXXVVWVVWWXXWXXWVþ
XXWVVVXVVWWXVWVVWWWXWWWVþWWWXXVVWWVVWWVXVWVWXWWXXVXXVþXXVVVWWWWWVVWWWWVVWWXXXXWXXXXXVVþWVVWVVVVWXXWWWXXWWWWXXVVXWVWþVVVWXXWVVWWVXVWWVVVVWVVWþ
XVWWVWWVWWVVVWWXVWVWþXWXWXXWWVXVWWVXXþVWWVVWWWWWVVþXXXXXVVVþWWVVÿþVVXVþVWXWVVVWþXVVXVXXWSPPPþXXWVXVWVSPPPPSWWþVXWXXXVVSPPPPSXWXXSPþ
XXWVVVXVSPPPPSVVWWSPPPPSþWWWXXVVWSPPPPSXVWVSPPPPSVXXVþXXVVVWWWSPPPPSWWVVSPPPPSWXXXXXVVþWVVWSPPPPSXWWWSPPPPSXXVVXWVWþSPPPPSWVVWSPPPPSVVVVWVVWþ
PSWWVWSPPPPSVWWXVWVWþXWSPPPPSVXVWWVXXþPPPSVWWWWWVVþXXXXXVVVþWWVVÿþVVXVþVWXWVVVWþPPPSVXXWVXVVþXXSPPPPSXXVWXXWWþPSWXXXSPPPPSWXXWXXWVþ
SPPPPSXVVWSPPPPSWWWXWWWVþWWWXSPPPPSVWWVSPPPPSWWXXVXXVþXXVVVWWWSPPPPSWWVVSPPPPSWXXXXXVVþWVVWVVVVSPPPPSXXWWSPPPPSXWVWþVVVWXXWVSPPPPSWWVVSPPPPSþ
XVWWVWWVSPPPPSWXVWSPþXWXWXXWWSPPPPSXXþVWWVVWWWSPPPþXXXXXVVVþWWVVÿþVVXVþVWXWVVVWþXVVXVXXWSPPPþXXWVXVWVSPPPPSWWþVXWXXXVVSPPPPSXWXXSPþ
XXWVVVXVSPPPPSVVWWSPPPPSþWWWXXVVWSPPPPSXVWVSPPPPSVXXVþXXVVVWWWSPPPPSWWVVSPPPPSWXXXXXVVþWVVWVVVVSPPPPSXXWWSPPPPSXWVWþVVVWXXWVSPPPPSWWVVSPPPPSþ
XVWWVWWVSPPPPSWXVWSPþXWXWXXWWSPPPPSXXþVWWVVWWWSPPPþXXXXXVVVþWWVVÿþVVXVþVWXWVVVWþXVVXVXXWVXVVþXXWVXVWVXXVWXXWWþVXWXXXVVSPPSWXXWXXWVþ
XXWVVVXVSPPPPPPSWWWXWWWVþWWWXXVVWSPPPPSSPPPPSWWXXVXXVþXXVVVWWWSPPPPSWWVVSPPPPSWXXXXXVVþWVVWSPPPPSXWWWXXWWSPPPPSXWVWþSPPPPSWVVWSPPSWWVVSPPPPSþ
PSWWVWSPPPPPPSWXVWSPþXWSSPPPSSPPPPSXXþPPPSVWWWSPPPþXXXXXVVVþWWVVÿþVVXVþVWXWVVVWþPPPSVXXWSPPPþXXSPPPPSSPPPPSWWþPSWXXXSPPPPPPSXWXXSPþ
SPPPPSXVVWSPPSVVWWSPPPPSþWWWXSPPPPSVWWVXVWVSPPPPSVXXVþXXVVVWWWSPPPPSWWVVSPPPPSWXXXXXVVþWVVWVVVVSPPPPSSPPPPSXXVVXWVWþVVVWXXWVSPPPPPPSVVVVWVVWþ
XVWWVWWVSPPSVWWXVWVWþXWXWXXWWVXVWWVXXþVWWVVWWWWWVVþXXXXXVVVþWWVVÿþVVXVþVWXWVVVWþPPPSVXXWVXVVþXXSPPPPSXXVWXXWWþPSWXXXSPPPPSWXXWXXWVþ
SPPPPSXVVWSPPPPSWWWXWWWVþWWWXSPPPPSVWWVSPPPPSWWXXVXXVþXXVVVWWWSPPPPSWWVVSPPPPSWXXXXXVVþWVVWSPPPPSVVWWSPPPPSXXVVXWVWþSPPPPSWVVWSPPPPSVVVVWVVWþ
PSWWVWSPPPPSVWWXVWVWþXWSPPPPSVXVWWVXXþPPPSVWWWWWVVþXXXXXVVVþWWVVÿþVVUUþVVWVVWUUþVVWVWZZWVWUUþVVWVWWVUZZZWVWUUþVVWVWUZZZWVUZZZWVWUUþ
VVWVWZZWVUZZZWVUZZZWVWUUþVVWVWWVUZZZWVUZZZWVUZZZWVWUUþVVWVWUZZZWVUZZZWVUZZZWVUZZZWVWUUþZZZWVUZZZWVUZZZWVUZZZWVUVZZWþZZZWVUZZZWVUZZZWVUZZZWUWþ
ZZZWVUZZZWVUZZZWVUZWþZZZWVUZZZWVUZZZWþZZZWVUZZZWVWþZZZWVUZWþZZZWÿþUTWXþXUTWXXXXþXXUTWXXXXXUTþXXXUTWXXXXXUTTTTþXXXXUTWXXXXXTTWXXXXXþ
XXXXXUTWXXXXXUTWXXXXXUTWþWXXXXXUTUTTUTUUTWXXXXXUTWXXXþUUTUUTUUTWXXXXXUTWXXXXXUUTUUTTUTþXXXXUTWXXXXXUTWXXXXXUTWXXXXXþXUTWXXXXXUTWXXXXXTTWXXXXþ
WXXXXXUTTUTTTUUTWXXXþUTUUTWXXXXXUTWXXþUTWXXXXXUTWXþXXXXXUTWþXXUTÿþ§§¥¦þ¨¦¦¦¤¥§¦þ¥§¤¦¥¥§§¥§§¨þ¥§¨¨¨¨¥¥¥§¥¨§§¥¤þ¨§¥¥§¤¥¥©§¤¦¦¤¤¤¦¦©©þ
¦¥¨¨¥¥¦¦¥¤¤¤§¦ª¦¦©¦¦¤¥¥ªþ©§¥§¨¦©¨¨§¦¥¥§¥¦¥¥¦§¥¥¥¥¨§§¥þ§¥¦¥£¤¥¥§¤¤¤¦¦¦¨¥§¤¤§¨¦¤¥¤¥¤¥¦£¥þ¦¨¨§©§¥¦¦©§¥¨¥¥¤¦¦¥¨¦¦§¦¦§¥¦þ¥©¦§¦¥¤¥¦£¤¥¤¤¦¤¤¤¥§¦©¨©þ
¦¦¥¦©¦¦¦¦¦¥¥§¨¦§¥£¤¥þ¦¥¨¨¥¨¥¥¥¥¥§§¦©©þ¥§¥¦§¦¦¥¦§¦¤þ¦¤¤¤¥¥¦¨þ§©§¥ÿþ¦¥§§þ¨¦¦©¥¨¨§þ¦¦_®©^©­ª¨¦§þ¥¦§š«ª©¨©¬«_©ª©¨þ¥§¬§§©«ª©ªª¬ªª©ªª_¥¦þ
¨¥¦¨ª§¨^©ª©©©ª©ª^ª¬_¤¥¨¦þ¤§¨¥¤©ª©ª¬­©©¨©__ª__«¨¦¤£§¥¤þ§¦¤¤¦¦¨¨©^©©¨©¨_©©^ª__®ª©š§¥¤§§¨þ§¥¤¤§¨¨«ª¨¨¥¥¦§ª^ªªª¦¥¥§¥¦¥þ¨§¦©©¦¦¥¦¦¤£¦©§©ª§§¥¥¥¦¨þ
¨¨¨¦¥¦¦¤¨©©¥¦§¨£¥§¦¤þ¨¨¦¦¨¦¨¦¤¥¤¥¥¦¥¤þ¥¤¨§¨¥¥¦¦§¤§þ¤¥¥¦¥¥¤¥þ¦¦©¦ÿþúúúþúûúúúûþúú
ûúúúþú
ûúú

ú


ûþú
ûûûûúúúú

úþ	ú
ûûûûûûûúûúûúúúú

úþûûûûûûúûûûûúú
úþûûúûúûûûúûûúúûûûúúþûûûûûûúúûúûûúúúúúûþûûûûûûûúûúúúúûúûúúúúúûþ	ûûûûûûûûûûûúúúúúûúúþûûûûûûúúúûúûúþúûûûûûûûûûúúþúúúþûûúúÿþVôþVôôVVVþUôôVVVVVVVþUUUôVVVVVVVVþUUUUUôVVVVVVVVþVôôVUUUUUôVVVVVVVVþVôôVVVVVUUUUUôVVVVVVVVþ
UVVVVVVVVVUUUUUôVVVVVVVVþUUUôVVVVVVVVUUUUUôVVVVWWþUUUUUôVVVVVVVVUUUUUôWWXWþVôôVUUUUUôVVVVVVVVUUUUXXXVþVôôVVVVVUUUUUôVVVVVVVVUUXVXXþUVVVVVVVVVUUUUUôVVVVVWXXXXXVþUUUôVVVVVVVVUUUUUôVVWXXXXXXVþUUUUUôVVVVVVVVUUUUUôXVXXXVUSþVôôVUUUUUôVVVVVVVVUUUUXXXVUSQRVôôVVVVVUUUUUôVVVVVVVVUUXWXSQQQSUVVVVVVVVVUUUUUôVVVVVWXXXVXRPQQQUUUôVVVVVVVVUUUUUôVVWXWXXQQSRQSUUUUUUôVVVVVVVVUUUUUôXXVRPQQQSUXWþUUUUUôVVVVVVVVUUUUXXXSRQSUXWþUUUUUôVVVVVVVVUUXXXQSUXWþ
UUUUUôVVVVVWXXXXWUXWþUUUUUôVVWXXXVUXWþUUUUUôXXXUXWþUUUUXXWWþUUXWÿþWWõõþWWõõWWWWþVõWWWWWWWWþVVVõWWWWWWWWþVVVVVõWWWWWWWWþWõõWVVVVVõWWWWWWWWþWõõWWWWWVVVVVõWWWWWWWWþ
VõWWWWWWWWVVVVVõWWWWWWWWþVVVõWWWWWWWWVVVVVõWWWWXXþVVVVVõWWWWWWWWVVVVVõXXYXþWõõWVVVVVõWWWWWWWWVVVVYYYWþWõõWWWWWVVVVVõWWWWWWWWVVYWYYþVõWWWWWWWWVVVVVõWWWWWXYYYYYWþVVVõWWWWWWWWVVVVVõWWXYYYYWVTþVVVVVõWWWWWWWWVVVVVõYWYWVTRSþWõõWVVVVVõWWWWWWWWVVVVYYYWRRRTWõõWWWWWVVVVVõWWWWWWWWVVYXYTPRRRVõWWWWWWWWVVVVVõWWWWWXYYYWYTSRTVVVVõWWWWWWWWVVVVVõWWXYXYYWYTTVXXVVVVVõWWWWWWWWVVVVVõYYWYXWYWXXWWWVVVVVVõWWWWWWWWVVVVYYYWYYYXWXYWWWWVVVVVVõWWWWWWWWVVYYYXYYYWYYYYWVYVWVVVVVVõWWWWWXYYYYXWYYYXYYYYVYVWWWXVVVVVVõWWXYYYWYYYYWYWYYYYWVYWWYWWWVVVVVVõYYYXYYYYXYWYXWYYWWWVWWWWWWWVVVVVYYXYYWXWXXXYYWWYRTYWWWVVVWWWWVVVYXWYXWYWWYWXYYVTPPRTYWWWWWVWVWWWYXYYYYYYYYXXVTRSPPRPRTVVVWWWWYWWYXXYYYYWYYVTRRRTPRTPPPRTWVWYWWWXYYWYYXYXVTRSPRRRTRPPPPRPRTYYWWYWYYYXYWVTRRRTSRTVYYTRPRTPPPRTYVVYYYXYVTRSPRRRTVWWþYYTRPPPPRPRTWWYXVTRRRTSRTVWWþYYTRPRTPPPRTVTRSPRRRTVWWþ
YYTRPPPPRPRRRTSRTVWWþYYTRPRTPPRRRTVWWþYYTRPPSRTVWWþYYTRTVWWþYYWWÿþWWWWþWWWWWWWWþWWWWWWWWXXþWWWWWWWWXXYYþWWWWWWWWXXYYYYþWWWWWWWWXXYYYYWWWWþWWWWWWWWXXYYYYWWWWWWWWþWWWWWWWWXXYYYYWWWWWWWWXXþõõWWWWXXYYYYWWWWWWWWXXYYþVVõõXXYYYYWWWWWWWWXXYYYYþVVVVYYYYWWWWWWWWXXYYYYWWWWþVVVVYYWWWWWWWWXXYYYYWWWWWWWWþVVVVVVõWWWWWXXYYYYWWWWWWWWXXþRTWVVVVõWWXXYYYYWWWWWWWWXXYYþPPRTWVVVXXYYYYWWWWWWWWXXYYYYþPPRPRTWVYYYYWWWWWWWWXXYYYYWWWWþPRTPPPRVYYWWWWWWWWXXYYYYWWWWWWWWTRPPPPRVVVõWWWWWXXYYYYWWWWWWWWXXXXTRPRTVVVVõWWXXYYYYWWWWWWWWXXYYXYWXTRPWVVVVXXYYYYWWWWWWWWXXYYYYWWXYWXTWWVVVYYYYWWWWWWWWXXYYYYYYXWWWXYWWWYVVYYWWWWWWWWXXYYYYYYYYWVYVWVXWWVWVVVõWWWWWXXYYYYYYYXYXVYVWWWVWXWWVVVVõWWXXYYYYYYYWYYXYWVYWWYWWWWXWVVVVXXYYYYYYXYWYXWYYWWWVWXWYWVYWWVVVYYYYYYXWXXXYYWWYRTYWWWVXVWWXWWVVYYYYXWYWWYWXYYVTPPRTYWWWWWVWVWWVYYYYYYYYYYXXVTRSPPRPRTVVVWXWWYWWYXYXYYYWYYVTRRRTPRTPPPRTWVWYWVWXYYWYYXYXVTRSPRRRTRPPPPRPRTYYWWYWYYYXYWVTRRRTSRTVYYTRPRTPPPRTYVVYYYXYVTRSPRRRTVWWþYYTRPPPPRPRTWWYXVTRRRTSRTVWWþYYTRPRTPPPRTVTRSPRRRTVWWþ
YYTRPPPPRPRRRTSRTVWWþYYTRPRTPPRRRTVWWþYYTRPPSRTVWWþYYTRTVWWþYYWWÿþWWXþWWWWWWXþWWWWWWWXXXþWWWWWWWXXYYYþWWWWWWWXXYYYYYþWWWWWWWXXYYYYYWWWWþWWWWWWWXXYYYYYWWWWWWWWþWWWWWWWXXYYYYYWWWWWWWWXXþõõWWWXXYYYYYWWWWWWWWXXYYþVVõõXYYYYYWWWWWWWWXXYYYYþVVVVYYYYWWWWWWWWXXYYYYWWWWþVVVVXYWWWWWWWWXXYYYYWWWWWWWWþVVVVVVõWWWWWXXYYYYWWWWWWWWXXþVVVVVVVõWWXXYYYYWWWWWWWWXXYYþRTWVVVVVXXYYYYWWWWWWWWXXYYYYþPPRTWVVVYYYYWWWWWWWWXXYYYYWWWWþPPRPRTWVXYWWWWWWWWXXYYYYWWWWWWWPRTPPPSVVVõWWWWWXXYYYYWWWWWWWWXTRPPPPRSVVVõWWXXYYYYWWWWWWWWXXYXYTRPRTPSVVVXXYYYYWWWWWWWWXXYYYþXYTRPPSVVVYYYYWWWWWWWWXXYYYYþXYTRPSVVYYWWWWWWWWXXYYYYþ
XYTRSVVVõWWWWWXXYYYYþXYTSVVVõWWXXYYYYþXYSVVVXXYYYYþXSVVYYYYþXYYYÿþ¨þ¨ª¨ª©þ¨¨©«©©ª«þ«¨«§¨ª©¨ªþ©ª¨ª§§¨ª©¨þ[ª¨¨©§¨¨«ªþ¬ùþ\ùª©¨ªª©«©þ«ª©ù[þ¬©§¨[«¬¬ª«þü¥¥¨ªªþ¬¨¦¨«ªü««©«þü¤¤§ð¥ü[þ©««¬[ü[þ¬¥¢¨¨¦\ùþZªþ\þ¤¥¦þ¬©¥§¨©\þZZYþ¥¤¥¦\þ
«§¨«««[þ¬««þ¦¥¥§\\¬þ§¨ª©©ª\þùZ«þ¨¥¥©[\[þ	¨©©¦©\þù«þ©¦©¬¬\þ[¬«¬ü©þ\[¬«þü©ÿþ¦¨«þª©¨¦¥§©ª«þ¤¤§§§©©¨©©ªþªªª©«ª§§¦§§§¨¨¦§¨¨«þ¨¨§©©©««¥§£¤¦¨ª¦¥¨¨«þ«¨¨©ª©ªª§¨¨§§©§¨§©§«ªþ¨û«ªª©©¨§§©¨©¨©ª¦««¦©þ««««ª©¦§¨§¨«ª©«©¥«««©ûþª«¨¦¨¦¦¨§¦§§§©©¨ª««¨¨þ«ª©©©¤¥««¨¨§¥¦¥¦¤¢¢¢¤¤¨«ª«¨þª©¨¨¨¦¤¨«§§¥¥¦££¢¥¥¢¤¤§«ª«©þ©©§¨©©¥¨«¨¨¨¤§£££¤¤¥§¥ªª«ª©þ©«©¨¦¥¨¨©¨©ª§©«§¦¥§¨©¥«ª«ª«þ«ª««««ª¨¨¨©¨©©©¨§¥¦¨ª§û«¨ª«þª©¨¨¨¥¦ª©¨¨©¨¨«ª«««þª¨¨¨¨¨ªYª«¨©©þ¨¨©¨¨¨ª©©©þ¨©©©¨ªª©ª¨þ©ª©¨¨¨©ªªþ©¨¨¨¨««ªªþ©©©¨¨ªª«þ©©©©¨þ©þ©©©ÿþññþññññññþEGññGEþEGIIFHIIGEþEGIIF;FHMHIIGEþEGII:;F;FHMH;:IIGEþ
ññEGIIþ:;F;FHMH;:þIIGEññþññññññþ:;þH;FHMHþ;:þññññññþGDññGEþ:;þI;HIMIþ;:þEGññDHþEIDGIIGE:;þ:;I:M:þ;:EGIIDGIGþðHDG:IIIGEþ;;:;M;þEGIIHIðGIGþðHDF:Iþ:IIGEM;;MMMEGII:þHIðFIFþGDDF:Iþ:;þIIGEññEGIIþ;:þHIðFDHþEIDF:I:;þEññññññEþ;:HIðFIGþðHDF:I:;þEIGDññDHIEþ;:HIðFIEþðHDF:I;þEIMEIDFIGMIEþ;HIðFIEþGDDF:I;MEIM;DHðFIG;MIEM;HIðFDHþEIDF:IMEIþDHðFIFþIEMHIðFIGþðHDF:IEIþGDðFDHþIEHIðFIEþðHDF:EIþEIðFIGþIEIðFIEþGDDFEE;:þDHðFIEþ:;EEðFDHþEIDFIIGE:þDHðFIEþ:EGIIðFIGþðHDFGIIIGEþGDðFDHþEGIIIHðFIEþðHDFIEþIIGEEIðFIGEGIIþEIðFIFþGDDFIGþIIDHðFIEIIþGIðFDHþEIDF:IEþ;DHðFIE;þEI:ðFIGþðHDF:IGþ::GDðFDH::þGI:ðFIFþðHDG:IIE::;;EIðFIG;;::EIIIðGIFþGDDG:IIG;;þDHðFIEþ;;GIIIðGDHþEIDG:I;IEþDHðFIEþEI;HIðGIGþDHDG:IþIGþGDðFDHþGIþGIDGIGþDHDG:IþIEþEIðFIGþEIþHIDGIGþDGþIGþDHðGIEþGIþDGþIEþDHðGIFþEIþIGþGDðGDHþGIþIEEIðGIGEIþIGDHðGIGGIþIDHDGIGIþDGÿþññþññññññþEGññGEþEGIIFHIIGEþEGIIFMFHOHIIGEþEEGGKMGNGHOHMLIIGEþ
ññGGGHþIMFNGIOHMLþIIGEññþññññññþIKþIOHIOHþMLþññññññþNDññIFþIKþKOILOIþMLþFHññDIþMKIIIIIEþLþO}MMOLþMLþHIMGIKIþIMHILIKKIGþ}}MOOMþEGIKKMFIMIþIMGFIHþNMIIIONMNNOEGIILþM}LM}HþIDDEIIþMOþMMIGññBFIIþMLþM}KODMþIKGFIIMNþIññññññEþMMM}N}KLþFMHHMKLMþHMIDññDHKEþMNN}M}}IþHNMMNIMþFL}IKFIKL}IEþOM}}}}GþLDMMOMNOFL}}GLIMOM}}IE}OM}LNDLþMKONOMOGLþINLO}MþIF}M}}}KKþKONNOOHKþLDM}DNþKGM}N}}LþKO}}OILþLKM}KMþMI}N}OMþMDMMII}NþIOMNNIþMOKMMODNþKKNNOLKINþI}LNNKþMGHM}}OKMþFMLMMMMKHFþIDKMDMþEHKKOMMOOKþGMKMNHþMKIFKKO}KKDHKLþI}M}OMþIDIIMKþKMI}NONLMKþKOLODNþHKIMNMGþOM}NONMNþEI}M}K}þEMIINOKþN}NDNODNNMþGM}M}}NþGNKM}NMHOO}}}K}}KLNOMMEIIOL}}MþLDMM}NNIO}þN}O}}KþMMGIKNIODNþKKIM}M}MIþO}O}}IþEIMHMLOKMþHLIINLþMIþNDNODLþGIþIMIM}LþFMIMNLþIFþNKMIKHþEIþIMHN}MþHIþIGþGMHHIEþGIþIMþHFþKNIIIEþDIþIIþMDIIDGþFIþKINKIHKFDHþLMKMGLIFGIþNKMHLIFIþGKÿþGHþIMM	IGHþEEGIMM	IGHþE€GEGIMM	IGHþEGIEEEGIMM	IGHþIGEEE€GEGIMM	IGHþ	GHþIGEGIEEEGIMM	IGHþGIMM	IGHþIGEEE€GEGIMM	IGHþEEGIMM	IGHþIGEGIEEEGI	M	HþE€GEGIMM	IGHþIGEEE€GEGIGGþEGIEEEGIMM	IGHþIGEGIEFFGGþIGEEE€GEGIMM	IGHþIGEEG	M	þIGEGIEEEGIMM	IGHþIGIþIGEEE€GEGIMM	IGHþIGEGIEEEGI	M	HþIGEEE€GEGIGGþIGEGIEFFGGþGIGEEG	M	þEEGIGI	IGHþE€GEGIMM	IGHþEGIEEEGIMM	IGHþIGEEE€GEGIMM	IGHþ	GHþIGEGIEEEGIMM	IGHþGIMM	IGHþIGEEE€GEGIMM	IGHþEEGIMM	IGHþIGEGIEEEGI	M	HþE€GEGIMM	IGHþIGEEE€GEGIGGþEGIEEEGIMM	IGHþIGEGIEFFGGþIGEEE€GEGIMM	IGHþIGEEG	M	þIGEGIEEEGIMM	IGHþIGIþIGEEE€GEGIMM	IGHþIGEGIEEEGI	M	HþIGEEE€GEGIGGþIGEGIEFFGGþIGEEG	M	þIGIÿþKKþIMNMLILþKIKINOMKLNþIILHHKNONNLLþLOOKGEHKNNONIIþNONKHEFFIMNONLIKþ	OOþOLHIIGIKNOúúOMMLþFINOOMNLþMIEGIIMOúúúúúMKIþEGLNúOOOMúþKKLMONNMOúOúNIþGEIHMNúúúúOMþOMLOMKNMIMKIþGIKLMNMúúúúúúKþNMMMMIIIIHþMIKKMKNIMNúúúLHIþKIGGGLMLþNLIMOKIKLúúúOOMMþLILþMKIGGFMLNúúúOOMMþKHEHOMMMúúOOOLþIHIIKKúMMOLIþILKMNMMIHHþIKIHGIMMKþHFIMKLMHFGþGEIIILMMIHFHþIIMIIHGIMMMLIIþMMIIIGGGHKNúMLIHþ	KLþMKIIIFGINOúOMIGIþGINNMLKLþKIEHIINMLMNMMKIKþEEHKOúNMKMþKIMOúLKHGIMNMKþG@HGIKúúMLKIþOOMLHEGEIKIIþGGIHHGHKOOMIHIþúMHIIEFHIIþKGFGFDIFGINMLIIIþKIFFGKMKþKIFHIEFHILNMLLILþKIIþIGEEFFIHIINNMKIHþHFFILIHGHKMúNIþIIHIHEIGIMKIþMLGHIFHHIIþLHEEGLMMþHFHÿþHGþHGI	MMIþHGI	MMIGEEþHGI	MMIGEG€EþHGI	MMIGEEEIGEþHGI	MMIGEG€EEEGIþHGI	MMIGEEEIGEGIþHGþHGI	MMIGEG€EEEGIþHGI	MMIGþH	M	IGEEEIGEGIþHGI	MMIGEEþGGIGEG€EEEGIþHGI	MMIGEG€EþGGFFEIGEGIþHGI	MMIGEEEIGEþ	M	GEEGIþHGI	MMIGEG€EEEGIþIGIþHGI	MMIGEEEIGEGIþHGI	MMIGEG€EEEGIþH	M	IGEEEIGEGIþGGIGEG€EEEGIþGGFFEIGEGIþ	M	GEEGIGþHGI	IGIGEEþHGI	MMIGEG€EþHGI	MMIGEEEIGEþHGI	MMIGEG€EEEGIþHGI	MMIGEEEIGEGIþHGþHGI	MMIGEG€EEEGIþHGI	MMIGþH	M	IGEEEIGEGIþHGI	MMIGEEþGGIGEG€EEEGIþHGI	MMIGEG€EþGGFFEIGEGIþHGI	MMIGEEEIGEþ	M	GEEGIþHGI	MMIGEG€EEEGIþIGIþHGI	MMIGEEEIGEGIþHGI	MMIGEG€EEEGIþH	M	IGEEEIGEGIþGGIGEG€EEEGIþGGFFEIGEGIþ	M	GEEGIþIGIÿþKKþLILMNMIþNLKMONIKIKþLLNNONKHHLIIþIINONNKHEGKOOLþKILNONMIFFEHKNONþLMMOúúONKIGIIHLOþOOþIKMúúúúúOMIIGEIMþLNMOONIFþINúOúOMNNOMLKKþúMOOOúNLGEþIKMIMNKMOLMOþMOúúúúNMHIEGþHIIIIMMMMNþKúúúúúúMNMLKIGþLMLGGGIKþIHLúúúNMINKMKKIMþLILþMMOOúúúLKIKOMILNþMMOOúúúNLMFGGIKMþLOOOúúMMMOHEHKþILOMMúKKIIHIþHHIMMNMKLIþKMMIGHIKIþGFHMLKMIFHþHFHIMMLIIIEGþIILMMMIGHIIMIIþHILMúNKHGGGIIIMMþIGIMOúONIGFIIIKMþLKþKIKMMNMLMNIIHEIKþLKLMNNIGþKMNMIGHKLúOMIKþMKMNúOKHEEþIIKIEGEHLMOOþIKLMúúKIGH@GþIIHFEIIHMúþIHIMOOKHGHHIGGþKMKGFFIKþIIILMNIGFIDFGFGKþIIKþLILLMNLIHFEIHFIKþHIKMNNIIHIFFEEGIþINúMKHGHILIFFHþIKMIGIEHIHIIþIIHHFIHGLMþMMLGEEHLþHFHÿþGHHþIMM	IGHHþEEGIMM	IGHHþEàGEGIMM	IGHHþEGIEEEGIMM	IGHHþIGEEEàGEGIMM	IGHHþGHHþIGEGIEEEGIMM	IGHHþIMM	IGHHþEEIGEEEàGEGIMM	IGHHEEGIMM	IGHHIààààEIGEGIEEEGI	M	HHEàGEGIMM	IGHHEààààEIGEEEàGEGIGGGEGIEEEGIMM	IGHHEààààEIGEGIEFFGGGIGEEEàGEGIMM	IGHHEààààEIGEEG	M		þIGEGIEEEGIMM	IGHHEààààEIGIIþIGEEEàGEGIMM	IGHHEàEIIþ
DõIGEGIEEEGI	M	HHEFGHHþ
õöøõIGEEEàGEGIGGGIFFGGþ
õøöõDIGEGIEFFGGGHFFFFþ
DõõàDDDõIGEEG	M		HFFFFþ
DDDDDDõöøõIGIIIIIGDDFFþ
DDDDDDõøöõDIIHHEDIGFFþ
DDDDDDDõõàDDHHFDIIDDFFþ
DõõàDDDDDDDGGGIDàIGFFHþ	õöøõàDDDDDDDFFDàIIDDFFIGHþIMMõøöõDDDDDDDFFGIDàIGFFM	IGHþEEGIMõõàDDDõõàDFFDàIIFFFHI	M	HþEàGEGIMMFDõöøõàDFFGIFFFHàGEGIGGþEGIEEEGIMMõøöõDFFFFFHGEGIEFFGGþIGEEEàGEGIMõõàDDFFFHþIGEEG	M	þIGEGIEEEGIMMFDFFþIGIþIGEEEàGEGIMM	IGHþIGEGIEEEGI	M	HþIGEEEàGEGIGGþIGEGIEFFGGþIGEEG	M	þIGIÿþKKþIMNMLILþKIKINOMKLNþIILHHKNONNLLþLOOKGEHKNNONIIþNONKHEFFIMNONLIKþ	OOþOLHIIGIKNOúúOMMLþFINOOMNLþMIEGIIMOúúúúúMKIþEGLNúOOOMúþKKLMONNMOúOúNIþGEIHMNúúúúOMþOMLOMKNMIMKIþGIKLMNMúúúúúúKþNMMMMIIIIHþMIKKMKNIMNúúúLHIþKIGGGLMLþNLIMOKIKLúúúOOMMþLILþMKIGGFMLNúúúOOMMþKHEHOMMMúúOOOLþIHIIKKúMMOLIþILKMNMMIHHþELOKIHGIMMIþIIþ
IIþLEKKLOOMKLLþLFIIþ
KILKKLLKEEEEKECBLEKKIIþ
KKMLMNNNNNMMCFDCKLHIKIþ
MBCCNNLLLNNNCDFCKLúMKGIþ	NCDFCIGGFGFFFCCINOMúKFIGHþGINNOMFDCIGIGGFFFFLNNOMMMGMKIGHþEEHKOúCCONHCCCFEEGGINúMMLIIKMKHþGBHGIKúúMMMCDFBDFGIMMMNNGIFGIGGþGGIHHGHKMMOCFDCDFFHIKúLIIKFFFGGþKGFGFDIFGINMCCBIFFFHþKIFEGKMKþKIFHIEFHILNMLLILþIGIþIGEEFFIHIINNMKIHþHFFILIHGHKMúNIþIIHIHEIGIMKIþMLGHIFHHIIþLHEEGLMMþHFHÿþ
°°°°°°°°°°þ°°°°°°°°°°°°°°þ°°°°°°°°°°°°°°°°°°þ
°°°°°°°°°°°°°°°°°°°°°°þ°°°°°°°°°°°°°°°°°°°°°°°°°°þ°RR°°°°°°°°°°°°°°°°°°°°°°°S°þ°ÐÐRR°°°°°°°°°°°°°°°°°°°STSUþRRÐÐÐRR°°°°°°°°°°°°°°°STSSÒSþ°ÐÐÐÐÐRR°°°°°°°°°°°STSSÐÐÓSþ°ÐÐÐÐÐÐÐRR°°°°°°°STSSÐÐÐÑÓSþRRÐÐÐÐÐÐÐÐRR°°°°°STSSÐÐÐÐÐÐÒ°þ°ÐÐÐÐÐÐÐÐÐÐRR°RSTÐÒÐÐÐÐÐÐÐÒUþ°ÐÐÐÐÐÐÐÐÐÐÐÒ°TÐÐÐÑÐÐÐÐÐÐÐÒSþ°ÐÐÐÐÐÐÐÐÐÑÐÒ°TÐÐÐÑÐÐÐÐÐÐÐÒSþRRÐÐÐÐÐÐÑÑÑÑÓ°TTÓÓÓÐÐÐÐÐÐÐÒSþ°ÐÐÐÐÐÒÓÒÑÒÓRRTÓÒÓÓÐÐÐÐÐÐÒ°þ°ÐÐÐÒÓÒÒÒÒÓÓÑ°TÓÒÓÓÓÔÑÐÐÐÒUþ°RÑÓÔÓÐÒÒÒÓÒÐ°TTÓÔÓÓÔÑÐÐÐÒSþ°°ÒÓÔÒÐÒÒÑÒÒÐRRTÓÔÓÔÒÐÐÐÐÒSþ°°°SÒÑÐÔÔÑÔÒÐÐ°TÐÒÓÔÓÑÐÐÐÒSþ°°°°°°SÑÔÔÒˆÔÐÐ°TÐÔÔÔÓÒÒÒÑÒ°þ°°°°°°°°SˆÒˆÐÓÔ°TTÔ‰ÔÓÓÓÒÒVUþ°°°°°°°°°°°SˆÐˆ‰RRTÔˆÔÔÓÓUTVSþ°°°°°°°°°°°°°S‰‰:°TÔ‰ÓÓUTSTVSþ°°°°°°°°°°°°°°°°S:°TÓˆUTSTTTVSþ°°°°°°°°°°°°°°°°°°°TVSSTTTTTV°þ°°°°°°°°°°°°°°°°°°°°TVSTTTTTTVUþ°°°°°°°°°°°°°°°°°°°RTVSTTTTTTVS°°°°°°°°°°°°°°°°°°°°TTVSTTTTVVVT°R°°°°°°°°°°°°°°°°RTTVSTTVVVTTTþ°°°°°°°°°°°°°°°°°TTTVTVVVT°Uþ°R°°°°°°°°°°°RTTTVVVTTTþ
°°°°°°°°°°°°TTTTT°UTþ°R°°°°°°RTTTTTTþ°°°°°°°TT°UTþ°R°RTTTþ°°UTÿþ÷þ÷ôþ÷ôþ÷ôþôôþòôþ÷þôòþôôþðòþòòþôôþòôþòôþôòþðôþô÷þðòþô÷þðòþô÷þòðþô÷þòðþðôþ÷÷÷÷òðÒ÷þòôþ÷÷ÐòðÑ÷÷÷÷þòðþ÷ÑÐÔÔÑòûþ
ð÷þ÷ùÑÔÔÒˆòû÷÷÷þòðþ÷ùùˆÒˆùôôü÷÷÷þ÷ðþþ÷ùùRˆùô÷ü÷÷÷þòðþRùùRRRô÷üùùù÷÷÷÷÷÷ðþRRRRQRRRô÷üúùùùùùùôUþQRRRRRRRQRRQR÷üúúùùùùùùù÷SþRQQQUQRRQ°°°RQRðúùùùùùùùôWþ°STTTUQQR°°QQQRRRðúúùùùùúúùU°°RR°SUUTR°RQQQRRRR°úúúúúúúúWV°S°°RSRRR°°QQQRRRQRWVUVþ°°°°RRS°°°RRQQQ°°ð
WSVþ°S°°°°°°RQQS°Sð
WWþ
°°°°°°°SRSRSV	
V
Wþ°R°°SSSSTVWW			þ°°RRSSTUUSVVþRTRTUTTþ°RVUÿþððððþðððäðòððþôðþðþðþôþððòðäðòäòðäðòäððþððþðþðþðþðþðþððþ
ôäòðäðòäòðäðòäòðäðòäòôþððþðþðþðþðþðþðþðþðððþðððäòðäðòäòðäðòäòðäðòäòðäðòäòðððþððþðþðþðþðþðþðþðþðððþððäòðäðòäòðäðòäòðäðòäðððþ
ððþðþðþðþðþðþððþððòðäðòäòðäðòäððþðððþðþðþððþðððäðòððþððððÿþóðóþ
ð
þñþðóðþð
ðþñþñþóðóþ
ð
þñþðóðþð
ðþñþñþóðóþ
ð
þñþðóðþðþ
þðþðþðþñRRRñþóRRRóþñ
RRR
ñþóþRRRþóþñ
þRRRþ
ñþóþRRRþóþñ
þRRRþ
ñþóþRRRþóþñ
þþ
ñþóóþðððþóóþ
óþóóóþó
þ
óþ			þó
þ
ó			ó
þ
			
þ			ÿþþþþñþñþñþñþþñþñþñþþþþþþþþý	ÿþþþþðVW·þðW··WYþ[ZZYZYZ\[Zþ[[þ[ZYZ\þ][þ[Z\[ZY[\þ[ZZYZZZþ[[þ[þþþþþþý	þ9µ£Zþ£Zÿþ
	þ
	þ	
þ

þð
þð	þð
þðð	þ	
Qþð	ðQþððQþ

Qþ	QþðQþ
QþðQþ	Qþþ	QþþQþþ	ýÿ
þWU

þWþVWUð
þVVU<	þ<
þUð]<	þVVZ\þ]]þ][\þU·[þ]þ][\þVWY[þ\]þ\ZY[\þU·Y\]]\]
·YZ\\þV	W·YZþ<UWUþ
UQþ<Qþ	Qþþ	QþþQþþ	ýÿþ
LþGLþLOLþGOLþLOLþGOOOLþLOGLþG–GLþLGLþGGLþLGLþLLÿþ
LþGLþLLþGOLLþLOLLþGOLLþLGLþGOL–GLþLGLþGGLþLGLþLLÿþLþLGþLLþLOLGþLOLLþLOLGþLGLþLG–OLGþLGLþLGGþLGLþLLÿþLþLGþLOLþLOGþLOLþLOOOGþLGOLþLG–GþLGLþLGGþLGLþLLÿþääþS	ääþSWþääþSWðþäþääþRWþðþðääþRWäþðþðþðþääþRWþðþðþääþRWäþðþðþðþðþäþääþRWþäþðþðþääþRWðþäþðþðþäþðþðþS	þRWþäþðþðþSWþRWäþðþäþäþðþäþðþSWþRWþäþäþðþðRWþRWðþäþäþäþäþðþäþRWþRWþäþäþðþRWþRWðþäþäþäþäþðþðþRWþRWþðþäþäþðRWþRWäþðþäþäþðþäþðþRWþSWþðþäþäþRWþSWðþäþðþðþäþðþäþRWþSWþðþðþäþäRWþSWäþðþðþðþðþäþðþRWþS	þðþðþäþRWþT	äþðþðþðþðþäþäþRWþT	þäþðþðþäRWþäþðþðþäþðþRWþäþðþðþðSWþäþðþäþðþSWþðþðSWþðþðþSWþðþS	þT	ÿþääþää	SþääþWSþääþäþðWSþääðþðþWRþääþðþðþðþäWRþääþðþðþWRþääþäþðþðþðþðþäWRþääþðþðþäþWRþ	SþðþðþäþðþðþäþðWRþWSþðþðþäþWRþWSþðþäþðþäþäþðþäWRþWRðþðþäþäþWRþWRþäþðþäþäþäþäþðWRþWRþðþäþäþWRþWRþðþðþäþäþäþäþðWRþWRðþäþäþðþWRþWRþðþäþðþäþäþðþäWRþWRþäþäþðþWSþWRþäþðþäþðþðþäþðWSþWRäþäþðþðþWSþWRþðþäþðþðþðþðþäWSþWRþäþðþðþ	SþWRþäþäþðþðþðþðþä	TþWRäþðþðþäþ	TþWRþðþäþðþðþäþWSðþðþðþäþWSþðþäþðþäþWSðþðþWSþðþðþ	Sþðþ	TÿþääþS	þSäääþSäþðääþRáäþðþääþRáþðþääþRòäþðþðþðþääþäþäþðþðääþRäðþäþðþðþäþðþäþRäþäþðþðäþRääþðþäþäþðþäþäþRäþäþäþðþäþRäðþäþäþäþäþðþäþRäþäþäþðäþRäðþäþäþäþäþðþäþRäþðþäþäþäþRääþðþäþäþðþäþäþRäþðþäþääþSäðþäþðþðþäþðþäþSáþðþðþäþäþSáäþðþðþðþðþäáäþSòþðþðþäáþääþðþðþðþðþäþäþT	ääþðþðþäþT	þääþðþäþðþäþääþðþðäþääþäþääþääþäääþäÿþääþ	SþäääSþääðþäSþääþðþäáRþääþðþáRþääþðþðþðþäòRþääðþðþäþäþäþðþäþðþðþäþðäRþäðþðþäþäRþäþäþðþäþäþðþääRþäþðþäþäþäRþäþðþäþäþäþäþðäRþäðþäþäþäRþäþðþäþäþäþäþðäRþäþäþäþðþäRþäþäþðþäþäþðþääRþääþäþðþäRþäþðþäþðþðþäþðäSþäþäþðþðþáSþäáäþðþðþðþðþäáSþáäþðþðþòSþäþäþðþðþðþðþääþäþðþðþää	Tþäþðþäþðþääþ	Tþäðþðþääþäþääþääþääþäääþäÿþääþðôääþðôþäþò÷ðþò÷þðþô÷äþð÷þðôäþäþôôþäþô÷ðþðþôôþðþôôäþðþòþòôþäþðòþä÷ðþäþôþò÷þðþðþ÷òðþðþðþ÷òþðôþòòþðþôþäòþäþôþò÷ðþäþðþäþôþä÷þðþäòþò÷äþðþäþò÷þäþòþò÷äþäþ÷þ÷÷þäþä÷þäþðþ	òþäþðþðþðäþäþðþäþðþòþðþðäþðþðþòþðþòþòÿþääþääôðþäþôðþð÷òþðþ÷òþä÷ôþ÷ðþäþäôðþääþôôþôðþð÷ôþôðþôôþ÷òþðþäôôþ÷òðþäþôòþ÷ôþäþð÷äþ÷ðþðþ÷òþôðþðþðò÷þôôðþò÷þ÷ôþðþòòþôôþäþòäþôôþäþðþäþð÷òþôòäþðþ÷äþ÷äþðþä÷òþ÷òþäþ÷òþò÷þäþä÷òþò÷äþäþ÷÷þòòþ	ðþäþòäðþðþðþäþ÷òþðþäþðþäþ÷äðþðþ÷òþðþðþ÷òþðþ÷òÿþþþþþþþþþþþþþþþþþþþþþþþþþþþþþþþþÿþ
þ
þþþþþþ
þ
þþþþ
þ
þ
þþ
þþ
þþ
þþ
þ


þþþÿþþþþþþþþþþþþþþþþþþþþþþþþþþþþþþþþÿþ
þ
þþþþþþ
þ
þþþþ
þ
þ
þþ
þþ
þþ
þþ
þ


þþþÿþþþþ

þ
þ
þ
þ
þ
þ


þ


þ


þ


þ


þ


þ


þ


þ


þ

þ

þ

þ

þ

þ


þ


þ


þ


þ


þ


þ


þ

þ

ÿþññññþòòððþòôððññññþòù÷ùñðððþò÷äò÷ùððññññþòáðòô÷ùñðððþòááðòôäò÷ùððññññþòááòôðòô÷ùñðððþò÷ðôòôðòôäò÷ùððññþòùðòôðòôðòôðòùùþòùðòôðòôðòôäòùùþòùðòôðòôðòôðùùþòùðòôðòôðòôðùùþòùðòôðòôðòôðùùþòùðòôðòôðòôðùùþòùðòôðòôðòôðùùþòùðòôðòôðòôðùùþòùäòòôðòôðòäðùùþò÷äòòôðòôòáðùùþòáòòôäòòôPðùùþòááðòôäòòô÷÷äðùùþòááòôäòòôäòô÷ðùùþò÷òôòôðòòôäòò÷ðùùþòùðòòôðòòôäòòôäòùùþôôù÷òôðòòôðòòôäòùùþôôù÷ðòòôðòòôäòùùþôôù÷òôðòòôðòùùþôôù÷ðòòôðòùùþôôù÷òôðòùùþôôù÷ðòùùþôôòòùùþôôùùÿþññññþòòððþù÷ùôððññññþù÷òä÷ùùþñðððþù÷ôòðáäðþððññññþù÷òäôòðááäðþñðððþù÷ôòðôòááäùþððññññþù÷òäôòðôòôð÷ùùþ	ñðððþôòðôòðôòðùùùþððññþôòðôòðôòðùùùþðòùùþôòðôòðôòðùùùþäòùùþôòðôòðôòðùùùþðùùþôòðôòðôòðùùùþðùùþôòðôòðôòðùùùþðùùþôòðôòðôòðùùùþðùùþôòðôòðôòðùùùþðùùþäòðôòðôòòäùùùþðùùþáòôòðôòòä÷ùùþðùùþPôòòäôòòáäðþðùùþä÷÷ôòòäôòðááäðþðùùþ÷ôòäôòòäôòááäùþðùùþ÷òòäôòòðôòôò÷ùùþðùùþôòòäôòòðôòòðùùùþðùùþôòòðôòòðôò÷ùòùùþäòùùþôòòðôòòð÷ùþôôùùùþ	äòùùþôòòðôò÷ùþôôùùùþäòùùþôòòð÷ùþ
ôôùùùþðòùùþôò÷ùþôôùùùþðòùùþ÷ùþôôùùùþðòùùþôôùùðòùùþôôòòùùþôôùùÿþññññþððòôþññññððôù÷ùþðððñþùù÷äò÷ùþññññððþðäáðòô÷ùþðððñþðäááðòôäò÷ùþññññððþùäááòôðòô÷ùþðððñþ	ùù÷ðôòôðòôäò÷ùþññððþùùùðòôðòôðòôþùùòðþùùùðòôðòôðòôþùùòäþùùùðòôðòôðòôþùùðþùùùðòôðòôðòôþùùðþùùùðòôðòôðòôþùùðþùùùðòôðòôðòôþùùðþùùùðòôðòôðòôþùùðþùùùðòôðòôðòôþùùðþùùùäòòôðòôðòäþùùðþùù÷äòòôðòôòáþùùðþðäáòòôäòòôPþùùðþðäááðòôäòòô÷÷äþùùðþùäááòôäòòôäòô÷þùùðþùù÷òôòôðòòôäòò÷þùùðþùùùðòòôðòòôäòòôþùùòäþùùòù÷òôðòòôðòòôþùùòäþ	ùùùôôþù÷ðòòôðòòôþùùòäþùùùôôþù÷òôðòòôþùùòðþùùùôôþ
ù÷ðòòôþùùòðþùùùôôþù÷òôþùùòðþùùùôôþù÷þùùòðùùôôþùùòòôôþùùôôÿþðòòðþðññðþðòòòñòòòðþðññññññðþðòòòñòòòòñòòòðþ
ðññññññññññðþðòòòñòòòòñòòòòñòòòðþðññññññññññññññðþñòòòòñòòòòñòòòòðþðññññññññññðþ
ñòòòòñòòòòðþðññññññðþñòòòòðþðññðþðÿþòóóòþô÷÷ôòóóòþòóóòô÷÷ôòóóòþô÷÷ôòóóòô÷÷ôòóóòþòóóòô÷÷ôòóóòô÷÷ôòóóòþ
ô÷÷ôòóóòô÷÷ôòóóòô÷÷ôòóóòþòóóòô÷÷ôòóóòô÷÷ôòóóòô÷÷ôòóóòþô÷÷ôòóóòô÷÷ôòóóòô÷÷ôòóóòô÷÷ôòóóòþô÷÷ôòóóòô÷÷ôòóóòô÷÷ôòóóòô÷÷ôþô÷÷ôòóóòô÷÷ôòóóòô÷÷ôòóóòþ
ô÷÷ôòóóòô÷÷ôòóóòô÷÷ôþô÷÷ôòóóòô÷÷ôòóóòþô÷÷ôòóóòô÷÷ôþô÷÷ôòóóòþô÷÷ôÿþääðòþääðòþ÷ääðòþ÷÷ääðòþô÷÷ääðòþääðò÷ôþ÷÷ääðòþääðòþ÷÷äðþ÷ääðòþ÷÷ääää÷þ÷÷ääðòþô÷÷÷÷÷þô÷÷ääðò÷ôþô÷þ
ääðò÷ôþ÷÷ääðòþ÷÷þääðòþ÷÷÷äðþô÷þ÷ääðò÷÷þ÷÷ääää÷þô÷þ	÷÷ääðòþô÷÷÷÷þ÷÷þ
ô÷÷ääðò÷ôþô÷þääðò÷ôþ÷÷ääðòþò÷þääðòþ÷÷äðþôþ÷ääðòþ÷÷ääää÷þò÷þ÷÷ääðòþô÷÷÷÷þò÷þô÷÷ääðò÷ôþ
ôþðôþ÷÷ääðòþ÷÷äðþ÷÷ääää÷þô÷÷÷÷þðôÿþôðäðòðòôþðääðäðòþôäôþää÷òäôþð÷÷÷÷ôòäääääôþò÷÷÷÷þ÷þ÷÷÷÷÷þô÷ò÷þô÷þ÷÷òþ÷÷þôþô÷þôþô÷þ÷÷ôþ÷þ÷÷þ÷ôòðäðòþô÷þääðò÷þôðääðòþò÷þääðòþ÷äðþôþ÷ääðòþ÷÷ääää÷þò÷þ÷÷ääðòþô÷÷÷÷þò÷þô÷÷ääðò÷ôþ
ôþðôþ÷÷ääðòþ÷÷äðþ÷÷ääää÷þô÷÷÷÷þðôÿþääðòþääðòþ÷ääðòþ÷÷ääðòþô÷÷ääðòþääðò÷ôþ÷÷ääðòþääðòþ÷÷äðþ÷ääðòþ÷÷ääää÷þ÷÷ääðòþô÷÷÷÷÷þô÷÷ääðò÷ôþ÷÷þ
ääðò÷ôþ÷÷ääðòþ÷÷þääðòþ÷÷÷äðþô÷þ÷ääðò÷÷þ÷÷ääää÷þ÷÷þ	÷÷ääðòþô÷÷÷÷þô÷þ
ô÷÷ääðò÷ôþô÷þääðò÷ôþ÷÷ääðòþ÷÷þääðòþ÷÷äðþô÷þ÷ääðòþ÷÷ääää÷þò÷þ÷÷ääðòþô÷÷÷÷þôþô÷÷ääðò÷ôþ
ò÷þô÷þ÷÷ääðòþ
ò÷þ÷÷þ÷÷äðþ
ôþô÷þ÷÷ääää÷þ
ò÷þô÷þô÷÷÷÷÷þ
ò÷þ÷÷þô÷þð÷þ
ð÷þô÷þ÷÷þð÷þ
òþò÷þô÷þð÷þôþô÷þð÷þò÷þ÷÷þòþò÷þô÷þð÷þôþò÷þð÷þò÷þôþð÷þò÷þò÷þò÷þôþò÷þò÷ÿþôäðòþôääðòô÷þôääðäðòþääðþääðôôäää÷þôää÷÷÷þ÷÷þ÷÷þþô÷þòðäòþ	þ÷÷þ÷òðääòþþô÷þ	òðäðääþþô÷þäðääþþ÷÷þ÷÷äää÷÷ðääþþô÷þ÷÷÷÷ää÷÷÷þþò÷þ÷÷ôþ÷òþôòðòðäðôþôþ÷÷þòðäðääðþò÷þþôäôþò÷þ÷þôäò÷ääþôþ÷þôäääääòô÷÷÷÷ðþò÷þþ÷÷÷÷÷þ÷þ÷÷÷÷òþò÷þ÷÷þ÷ôþ÷ò÷ôþð÷þ÷þ÷÷þò÷÷þòþ÷þô÷þð÷þþô÷þð÷þ÷þ÷÷þòþ÷þô÷þð÷þôþò÷þð÷þò÷þôþð÷þò÷þò÷þò÷þôþò÷þò÷ÿþ÷÷þ÷÷þ÷÷þ÷÷þ÷ôþ÷÷þ÷ôþ
÷÷þ÷÷þ
÷ôþ
÷÷þ÷÷þ
÷÷þ
÷÷þ÷÷þ
÷ôþ
÷÷þ÷÷þ
÷÷þ
÷ôþ÷ôþ÷÷þ÷ôþ
÷÷þ÷÷þ÷÷÷þ÷ò÷þ	÷ôþ÷ôþ÷÷÷þ÷òþ÷þ÷ôþ÷ôþ÷÷þôþ÷þ÷÷þ÷÷÷÷þ÷ôþ÷òþ÷þ÷ôþ÷ðþ÷÷þ÷÷÷þ÷òþ÷þ÷÷ðòþ÷ðþ÷÷÷ôþ÷ðþ÷þ÷÷þðôþôðþ÷þ÷ôþòþ÷÷÷þðþ÷òþ÷òðþ÷þ÷÷÷÷þ÷ðþ÷÷þ÷þðþ÷òþ÷òþð÷þ÷ôþ÷÷÷÷þðþôþôþðþð÷òðððòþðþ÷þ÷òþ÷òþ÷ðððþôþ÷ðððþðþ÷þ÷òþ÷ò÷þðþ÷òþ÷ðþðððþ÷þ÷ðþ÷ððððþ÷òþ÷ðþðþðððþ÷òþðþðþôþðþððððþ÷ðþðþ÷òþðþ	÷ðþ÷ðþðþ÷òþðþ
òþòþðþ÷ðþðþ÷ðþ÷ðþðòþðþ÷ðþ÷ðþð÷ððþ÷ðþ÷ðþ÷ðþòþ÷ðþ÷ðþ÷ðÿþòðääþòðääþòðää÷þòðää÷÷þòðää÷÷ôþòðää÷÷þô÷òðääþðä÷÷þòðääþ÷ääää÷÷þòðää÷þ÷÷÷÷÷ôþòðää÷÷þ÷÷þô÷òðää÷÷ôþ÷÷þòðää÷÷þô÷òðääþ
÷ôþðä÷÷÷þòðääþ÷÷þ÷ääää÷÷þ÷÷òðää÷þ÷ôþ÷÷÷÷ôþòðää÷÷þ	÷ôþô÷òðää÷÷ôþ
÷÷þòðää÷÷þô÷òðääþ÷ôþðä÷÷þòðääþ÷òþ÷ääää÷÷þòðää÷þôþ÷÷÷÷ôþòðää÷÷þ÷òþ
ô÷òðää÷÷ôþ÷òþ
òðää÷÷þ÷ôþôþ
ðä÷÷þ÷÷þ÷òþ
÷ääää÷÷þ÷ôþ÷òþ
÷÷÷÷÷ôþ÷ôþ÷ðþ
÷ðþ÷ôþ÷÷þòþ
÷ðþ÷÷þ÷ôþ÷ðþ÷ôþ÷òþ÷ðþ÷ôþôþòþ÷÷þ÷òþ÷ðþ÷ôþ÷òþ÷ðþ÷òþôþ÷ðþôþ÷òþ÷òþ÷òþ÷òþôþ÷òþ÷òÿþòðäôþ÷ôòðääôþòðäðääôþðääþ÷äääôôðääþ÷÷÷ääôþ÷÷þ÷÷þ÷ôþþ÷÷þþ	òäðòþ÷ôþþòääðò÷þ÷ôþþääðäðòþ	÷÷þþääðäþ÷ôþþääð÷÷äää÷÷þ÷òþþ÷÷÷ää÷÷÷÷þôþôðäðòðòôþò÷þô÷÷þ÷òþðääðäðòþ÷÷þ÷òþôäôþþôþää÷òäôþ÷þ÷òþð÷÷÷÷ôòäääääôþ÷þ÷òþò÷÷÷÷þ÷þ÷÷÷÷÷þþ÷ðþô÷ò÷þô÷þ÷÷þòþ÷÷òþ÷÷þ÷þ÷ðþ÷ôþ÷þ÷ðþ÷ôþþòþ÷÷þ÷þ÷ðþ÷ôþ÷þ÷ðþ÷òþôþ÷ðþôþ÷òþ÷òþ÷òþ÷òþôþ÷òþ÷òÿþòðääþòðääþòðää÷þòðää÷÷þòðää÷÷ôþòðää÷÷þô÷òðääþðä÷÷þòðääþ÷ääää÷÷þòðää÷þ÷÷÷÷÷ôþòðää÷÷þ÷ôþô÷òðää÷÷ôþ÷÷þòðää÷÷þô÷òðääþ
÷ôþðä÷÷÷þòðääþ÷ôþ÷ääää÷÷þ÷÷òðää÷þ÷÷þ÷÷÷÷ôþòðää÷÷þ	÷ôþô÷òðää÷÷ôþ
÷òþòðää÷÷þô÷òðääþôþðä÷÷þòðääþ÷òþ÷ääää÷÷þòðää÷þ÷òþ÷÷÷÷ôþòðää÷÷þôþ
ô÷òðää÷÷ôþòðää÷÷þôðþðä÷÷þ÷ääää÷÷þ÷÷÷÷ôþôðÿþôòðòðäðôþòðäðääðþôäôþôäò÷ääþôäääääòô÷÷÷÷ðþ÷÷÷÷÷þ÷þ÷÷÷÷òþ÷ôþ÷ò÷ôþ÷÷þò÷÷þ÷ôþôþ÷ôþôþ÷÷þ÷þô÷÷þ÷ôþòðäðòô÷þ÷òþòðääðôþ÷òðääþôþðä÷þòðääþ÷òþ÷ääää÷÷þòðää÷þ÷òþ÷÷÷÷ôþòðää÷÷þôþ
ô÷òðää÷÷ôþòðää÷÷þôðþðä÷÷þ÷ääää÷÷þ÷÷÷÷ôþôðÿþ÷÷þ÷÷þ÷÷þ÷÷þô÷þ÷÷þ÷÷þ
ô÷þ÷÷þ
ô÷þ
÷÷þ÷÷þ
÷÷þ
÷÷þ÷÷þ
ô÷þ
÷÷þô÷þ
÷÷þ
÷÷þ÷÷þ
ô÷þ÷÷þô÷þô÷þ	÷ò÷þ÷÷÷þ÷÷þô÷þ÷þò÷þ÷÷÷þô÷þ÷÷þ÷þôþ÷÷þô÷þô÷þ÷þò÷þô÷þ÷÷÷÷þòð÷÷þ÷þò÷þ÷÷÷þ÷÷þð÷þôðþ÷÷þ÷þð÷þô÷÷÷þð÷þò÷þðþ÷÷÷þòþô÷þ÷þðôþò÷þðþ÷þ÷÷þð÷þ÷÷÷÷þ÷þðò÷þôþðþ÷÷÷÷þô÷þ÷ðþò÷þò÷þ÷þðþòðððò÷ðþðþôþò÷þ÷þðþððð÷þôþððð÷þò÷þð÷þ÷þðððþð÷þò÷þðþ÷ò÷þò÷þðððþðþð÷þò÷þðððð÷þððððþðþôþðþðþð÷þ	ðþò÷þðþð÷þòþ
ðþò÷þðþð÷þð÷þðþð÷þðþòþð÷þðþòðþð÷þð÷þðð÷ðþð÷þð÷þð÷þòþð÷þð÷þð÷ÿþðääðþðäþáäðþðäþáþáäðþðäþáþáþPäðþðäþáþáþáþPäðþ
ðäþáþáþáþPþáäðþðäþáþáþPþPþáþáäðþðäþáþPþPþPþáäðþ
ðäþáþPþPþáäðþðäþPþáþáäðþðäþPþáäðþðäþáäðþðääðÿþ„„þ„„ƒƒ‚‚þ„„ƒƒ‚‚‚‚‚‚þ„„ƒƒ‚‚‚‚‚‚‚‚‚‚þ„„ƒƒ‚‚‚‚‚‚‚‚‚‚‚‚‚‚þ„„ƒƒ‚‚‚‚‚‚‚‚‚‚‚‚‚‚‚‚‚‚þ  þ„„ƒƒ‚‚‚‚‚‚‚‚‚‚‚‚‚‚‚‚‚‚‚‚‚‚þ¢¢  ƒƒ‚‚‚‚‚‚‚‚‚‚‚‚‚‚‚‚‚‚‚‚‚‚‚‚ƒƒ¢¢¢¢  ‚‚‚‚‚‚‚‚‚‚‚‚‚‚‚‚‚‚‚‚‚‚ƒƒ„„¢¢¢¢¢¢  ‚‚‚‚‚‚‚‚‚‚‚‚‚‚‚‚‚‚ƒƒ„„„„¢¢¢¢¢¢¢¢  ‚‚‚‚‚‚‚‚‚‚‚‚‚‚ƒƒ„„„„……¢¢¢¢¢¢¢¢¢¢  ‚‚‚‚‚‚‚‚‚‚ƒƒ„„„„……þ¢¤¢¢¢¢¢¢¢¢¢¢  ‚‚‚‚‚‚ƒƒ„„„„……þ¢¤þ¢¢¢¢¢¢¢¢¢¢  ‚‚ƒƒ„„„„……þ¢¤þ¢¢¢¢¢¢¢¢¢¤ƒƒ„„„„……þ¢¤þ¢¢¢¢¢¢¢¤„„„„……‚‚þ¢¤þ„„¢¢¢¢¢¤„„……‚‚‚‚‚‚þ¢¤þ„„ƒƒ‚‚¢¢¢¤……‚‚‚‚‚‚‚‚‚‚þ¢¤þ„„ƒƒ‚‚‚‚‚‚¢¤‚‚‚‚‚‚‚‚‚‚‚‚‚‚þ¢¢  ƒƒ‚‚‚‚‚‚‚‚¢¤‚‚‚‚‚‚‚‚‚‚‚‚‚‚ƒƒ¢¢¢¢  ‚‚‚‚‚‚‚‚¢¤‚‚‚‚‚‚‚‚‚‚‚‚ƒƒ„„¢¢¢¢¢¢  ‚‚‚‚‚‚¢¤‚‚‚‚‚‚‚‚‚‚ƒƒ„„„„¢¢¢¢¢¢¢¢  ‚‚‚‚¢¤‚‚‚‚‚‚‚‚ƒƒ„„„„……¢¢¢¢¢¢¢¢¢¢  ‚‚¢¤‚‚‚‚‚‚ƒƒ„„„„……þ¢¤¢¢¢¢¢¢¢¢¢¢  ¢¤‚‚‚‚ƒƒ„„„„……þ¢¤þ¢¢¢¢¢¢¢¢¢¢¢¤‚‚ƒƒ„„„„……þ¢¢¢¢¢¢¢¢¢¤ƒƒ„„„„……þ¢¢¢¢¢¢¢¤„„„„……þ¢¢¢¢¢¤„„……þ¢¢¢¤……þ¢¤þ¢¤þ¢¤ÿþ  þ¢¢  þ¢¢¢¢  þ¢¢¢¢¢¢  þ¢¢¢¢¢¢¢¢  þ¢¢¢¢¢¢¢¢  þ¢¢¢¢¢¢  þ„„ƒ¢¢¢¢¢¢ ¡þ„„ƒƒ‚‚‚¢¢¢¢¢¤þ„„ƒƒ‚‚‚‚‚‚¢¢¢¢¤þ„„ƒƒ‚‚‚‚‚‚‚‚‚‚¢¢¢¤þ„„ƒƒ‚‚‚‚‚‚‚‚‚‚‚‚‚‚¢¤„„ƒƒ‚‚‚‚‚‚‚‚‚‚‚‚‚‚‚‚‚‚‚¢¤‡‡‚‚‚‚‚‚‚‚‚‚‚‚‚‚‚‚‚‚‚‚‚‚‚‚¤‡‡‡‡‚‚‚‚‚‚‚‚‚‚‚‚‚‚‚‚‚‚‚‚ƒƒ„¤‡‡‡‡‡‡‚‚‚‚‚‚‚‚‚‚‚‚‚‚‚‚ƒƒ„„„¢¤þ‡‡‡‡‡‡‚‚‚‚‚‚‚‚‚‚‚‚ƒƒ„„„„…þ¢¤þ‡‡‡‡‡‡‚‚‚‚‚‚‚‚ƒƒ„„„„……  þ¢¤þ‡‡‡‡‡‡‚‚‚‚ƒƒ„„„„……¢¢¢¢  ¢¤þ‡‡‡‡‡‡ƒƒ„„„„……¢¢¢¢¢¢¢¤þ„„‡‡‡‡‡‡„„……¢¢¢¢¢¤þ„„ƒƒ‚‚‡‡‡‡……¢¢¢¢¤þ„„ƒƒ‚‚‚‚‚‚‡‡‚‚¢¢¢¤þ„„ƒƒ‚‚‚‚‚‚‚‚‚‚‚‚‚‚¢¤„„ƒƒ‚‚‚‚‚‚‚‚‚‚‚‚‚‚‚‚‚‚‚¢¤‡‡‚‚‚‚‚‚‚‚‚‚‚‚‚‚‚‚‚‚‚‚‚‚‚‚¤‡‡‡‡‚‚‚‚‚‚‚‚‚‚‚‚‚‚‚‚‚‚‚‚ƒƒ„¤‡‡‡‡‡‡‚‚‚‚‚‚‚‚‚‚‚‚‚‚‚‚ƒƒ„„„¢¤þ‡‡‡‡‡‡‚‚‚‚‚‚‚‚‚‚‚‚ƒƒ„„„„…þ¢¤þ‡‡‡‡‡‡‚‚‚‚‚‚‚‚ƒƒ„„„„……þ¢¤þ‡‡‡‡‡‡‚‚‚‚ƒƒ„„„„……þ‡‡‡‡‡‡ƒƒ„„„„……þ‡‡‡‡‡‡„„……þ‡‡‡‡……þ‡‡ÿþùùþùúúúøþùúúúøöåþùúúúøöôôöþùúúúøöôôôôãþúûúåôôôôôôöþûûúöôôôöôôæþéûúãôôøö÷ôöþèçéúöôô÷öôôäþèèéêúæôøøøøôöþçþûûúöôù÷ôôôáþåþûûúäôôôôöþçþúûúöôôöþçþúúáöþôôþçþôóäòôþçþôóäòòðòôþçþôóàòòðòÄãòôþçþôóâòòðòÇãóô

þçèþ	óòðòÄãóô

þçþ		óÅãóô

þçþ			óô

þçþè


þçþçç

þèç

þ

ÿþùùþøúúúùþåöøúúúùþöôôöøúúúùþãôôôôöøúúúùþöôôôôôôåúûúþæôôöôôôöúûûþöô÷öøôôãúûéþäôôö÷ôôöúéçèþöôøøøøôæúêéèèþáôôô÷ùôöúûûþçþöôôôôäúûûþåþöôôöúûúþçþôôþöáúúþçþôòäóôþçþôòðòòäóôþçþôòãÄòðòòàóôþçþ

ôóãÇòðòòâóôþçþ

ôóãÄòðòó	þèçþ

ôóãÅó		þçþ

ôó			þçþ


èþçþ

ççþçþ

çèþ

ÿþ
éèêíêéëþëêìþéêëþèéêõþëëéêëóòòþëòééòëëêìôòúúþòèòææòåôôôôôóòúúþóëéåëååëåéëôóòúúþòòòóëèêææêéëôóúúþòòòòòòóëêèèêëôúúþööòòòòòóôêêôúúþööòòòòòôúúþìêþööòòúúþëééêþöúþèêçéëþòóôåêôôóòòþWVUUôóéêèéóòòòòòþUUUVVôóôèäåóòòòúúþVTTVWWôóéçåèóòúúþòôXUUXWXôòóôåôúúþòòòôZWWZYôóòòòúúþòòòòòó[\\[ôóòòúúþööòòòòóôôôóòúúþööòòòòòòúúþööòòúúþöúÿþòòþòòéêéèþòòéèæåèæóòþòòòéçæèéêèóòòòþòòòòêèèçôèéôòòùùþëëòòòêèéèôôôôòùùþòòëêêëòéèôôóòòùùþòòòòòèêìëêôóòòùùþòòòòòòòêëëêôóòùùþööòòòòòòéëôòùùþæþööòòòòòòùùþêéåèþööòòùùþèçåëþöùþòòêéëêëþòòòòòòéçéòþéòòòòòêëéëçòòòþêòòêòéêêèêëéôòùùþòòòéççèééëëôôôùùþòòòòòòêèêôóòòòùùþòòòòòòòòòóóòòòùùþòòòòòòòòòòòòòòùùþööòòòòòòòòòòùùþööòòòòòòùùþööòòùùþöùÿþUUVWþVVUUUþWWVTUUVWþòóXWXUVVUUUþòòòóôYZWWWVTUUVWþööòòóô[\XWXUVVUUUþööòòóôôYZWWWVTTVþööòòóô[\XWXUUXôòþööòòóóôYZWWZôòòòþþööòòòô[\\[óòòòòòþíþööòòóôôóòòòòùùþêþööòòòòòòùùþíþööéòùùþêþöùþóôêéèêíþéþòòòôìêéìêèþööòóôëêôêéèêíþööòóóôìêéìêþööòóôëêôêéèêéþööòóóôìêéìëòþööòóôëêôêéèêóòòòþööòóóôìêéìóòùùþööòóôëêôùùþööòòùùþöùÿþëéêíêèéþìêëþëêéþõêéèþòòóëêéëëþööòôìêëëòééòëþööòóôôôôôåòææòèòþööòóôëéåëååëåéëóþööóôëéêææêèëóòòòþööôëêèèêëóòòòòòòþööôêêôóòòòòòùùþêìþööôòòòòòùùþêééëþööòòùùþëéçêèþöùþòòóôôêåôóòþòòòòòóéèêéóôUUVWþööòòòóåäèôóôVVUUUþööòóèåçéóôWWVTTVþööôåôóòôXWXUUXôòþööòòòóôYZWWZôòòòþööòòóô[\\[óòòòòòþööòóôôôóòòòòùùþööòòòòòòùùþööòòùùþöùÿþþþ
þ—–þ–þ—–þ¥–þ—–––þ¥¥–—–––—þ——¥¥–—–––—þ——¥¥¥¥—––þ——¥¥—–—þ———¥¥—–—þ——¥¥—–——þ——¥¥—–—þ——¥¥—–—þ———¥¥—–——þ——¥¥—–þ—¥¥—–þ¥¥—–þ¥—–ÿþþ—–þ—––þ—–––þ—––—þ—–––—þ––—þ—––—þ¥¥–—þG¥¥–—þG¥¥¥–—þG¥—¥¥–þG¥——¥¥–þG¥———¥¥–þG¥————¥¥–]þG¥—————¥¥–]þG¥——————¥¥óþG¥———————¥óóþ¥————————óþ————————]þ———————]þ——————]þ—————]þ————óþ———óþ——óÿþþ—–þ—––þ—–––þ—–––þ—––—þ—–––—þ—–––—þ]—–––—þó––—þó–—þó——þ——þó——þó——þó——þ
—þ—þó—þ
óó—þ—þó—þóþÿþþ—–þ—––þ—–––þ—–––þ—–––þ—––—þ—–––—þ—–––—þ––—þó–—þó—þó—þ—þ—þ—þ—þóþþóþ
óþþþóþóóóóþóþóóþ
óóþóþóóþóóþóóÿþþþ————þ—–––—þ—––––––þ
—––––—–—þ—––––—–—þ—––––—–——––—–—–—––—–—–ó–—–—óó—–—óó—–—ó—–——–—ó—–—ó—–—óó—–—þ—–—þó––—óþó–——óþ–——þ——óþó——þó—þóóþ	óþóþóóóóþóþóóþóþóóóÿþþ—þ–—––þ–—þ—–—þ—–—þ——¥þ——–þ——–þ——–––þ—–––þ—–––þ—–––þ—––—þ—–––—þó––—þó–—þó—þ—þó—þó—þó—þ—þ—þó–þóþóþóþóþÿþóðñ
þóóúþ	úþ	úþ	þóðñ
þ	úúú
óóúþ	úþúú	úþ	úþ	úþ	úþ	úþóúþ	úþúúþ	úþ	úþ	úþúúþ	úþ
úþóúþúúþúúþúþ	úþúúþúúþúþ
úþðúþúúþóúþúþRûJ¥úúþRúúúúúþûRú¥ðúþúRJ¥óúþRRQQRRûúþóúðR¥úúþðúþðRûúþððþRúúþððþñúúþððþ
ð	úþððþðúþ	ððþððþððþððþððþððþððþððÿþóþúþúþúúðþúúñþ
úúúþ	úþ
úúúúúúúúúþ
	úþúúúúúúþ	úúþúþúúúþúú
þþ
ú	úþúú
þú
úúþ	úúþúúúþóúúþúþúúúþóóúúþúúúþóðúþúúþóóúþúúþóûþúúúúþóðúþóóúúþóûóúþðúúúþóúó



óóúúþóðó
þ	ñóûúúþóóúþóúúúþóóðúþóûúúþóó
ðþóóúúúþóó
þñóúúþó
þóþóðúúþó
þ
óþóðúþóóþ
óþðóó
þ
þ
óó
ÿþJJþþLLJJþþLLLLJJþþLJLLLNþþLHLJLNþþHGHJLHLNþHG¥¥GHJLþ
GGHHþ	þþþ°°°––þ°°–þ°°°°þ°°þ°þþ	þþþþÿþ	Wþ				þ	WWþ	þ
	þ	ñ		UVþ	þ



		[V			þ		
	
		[TVñþñ						[




WWWðþRððð		ðW[[
	þ°°°RRð		
[[	[	–ñþ°°R		

[		ðþ°ðð		[			ðþ°ñ		ñ			ð°þ°°°ðñðð	ñðð°°þ°°ðð°þ	°ððþ°þ°°°°þ°þÿþþþþþ––þ
––––þ––––——–þ––––———––––þ—–––––———————þ——––———————þ—–——–————þ
—––——–þ
—––––——––þ—––––––þ—–––––þ–––––þ–––þ––ÿþþ––þ–––þ–——–———þ––––———––––—¥¥—þ––––—————————¥¥¥¥—þ
———–———————¥¥¥¥¥GGHþ—–——¥¥¥¥¥——¥¥GGHHGGHGþ
—¥¥GGHHGGGGGHHþ
—–¥¥GHHG¥GHH¥þ—–¥¥¥G¥þ—–þ––––þ–––°°þþ––ÿþ¦¢µ  µ¢¦þ¢ ¢¥¥¢ ¢þ¢¢¦¦¥¥¥¥¥¦¦¦¢¢þ¢¥¤¤¤¢¢¢¥¦ µ¦¤¥¢þµ¥¤¤¢¢¢¢¢¢¤¦¦¤¢¤¥µþ©¢ µ¢¥¤¤¤¥¦¦¤¢µ ¢©þ¦¢  µ¤¦¦¤µ  ¢©þ¦¥¥¦¥¢   µ¢¦©¦¦¦þ¦¥¤¥¦¦¥¦¦¥¦¦þ¦¥¤¤¥¦¥¢¦¥¤¦¤¤¦¥¦¦þ¥¦¤¢¤¥¤¢¥¤¤¦¤¤¥¥¦¥þ¤¤¥¢¢¤¢¢¥¤¢¥¤¦¥¥¥¤þ¢ ¢¢¢¢¢¤¢¢¤¤¥¢µ¤©þ¤µ  µ¢¢¢¢¢µµ¥¦©©þ¦¥¥¦¢    µ¢¦©©¦¦þ¦¥¤¢¦¤¦¦¥¦¥¥¦þ¦¥¤¢¥¢¢¢¤¦¦¤¥¦¥¥¦¦þ¦¤¢¢¢¢¢¢¢¤¤¥¤¥¥¦¦þ¦¦¥¢¢¢¤¢¢¢¤¤¥¤¥¥¦¦þ¥¦¤¢¢¢¢¢¢¥¢¤¤¥©¦þ¥¤¦¦¤¢¢¢¢¥©©¥¦þ¦¤¥¦©©©¦¥¤¦þ¥¤¢¤¥¦ÿþ¦¢µ  µ¢¦þ¢ ¢¥¥¢ ¢þ¢¢¦¦¥—˜—B¦¢¢þ¢¥¤¤¤¢¢¢˜²µ˜§¥¢þµ¥¤¤¢¢¢¢¢¢¤¦¦¤¢¤¥µþ©¢ µ¢¥¤¤¤¥¦¦¤¢µ ¢©þ¦¢ ²µ¤¦¦¤µ  ¢©þ¦¥¥——˜¢   µ¢¦©¦¦¦þ¦¥¤–˜¦—¥¥¦¦þ¦¥¤¦¥¢¤¤¤¤¦¥¥¦¦þ¥¦¤B¤B¤¢¢¢¤¤¦¥¥¦¥þ¤¤¥B¢B¢¢¢¢¤¦¥¥¥¤þ¢ ¢¢¢¢¢¢¢¢¦¢µ¤©þ¤µB¤¢¢¢¢B¥¦©©þ¦¥¥¦BAB µ¢¦–©¦¦þ¦¥¤¢¢¤˜¦˜¦¥¥¦þ¦¥¤¢¢¢¢¥¤¤¤–¦¥¥¦¦þ¦¤¢¢¢¢¤¢¤¤¦¥¥¦¦þ¦¦¥¢¢¢¢¢¢¢¤¦¥¥¦¦þ¥¦¤¢¢¢¤¢¢¢¦¦©¦þ¥¤¦¦¤¥¥¢§˜©¥¦˜þ¦¤¥—˜—˜©¦¥˜–—þ¥¤¢¦˜þ——B—˜þ–˜©ÿ